### ISSUE TITLE
compilation failed with missing libraries

### ISSUE THREAD

**Issue by smrl** [PaulBatchelor/weewiki#1]
Building weewiki failed on this step:

cc -std=c89 -pedantic -g -Wall -O3 -I. -Wl,--export-dynamic -DWWSERVER janet/janet.c99 janet/init.gen.c99 janet/janet_main.c99 janet/line.c99 janet/janet_sqlite.c99 janet/jpm.gen.c99 janet/jpm.c99  weewiki.o jan.c99 keyscrape.o zet.o crate.o uuid4/uuid4.o linenoise/linenoise.c99 server.c99 -o weewiki  -lsqlite3 -lz 

To build I needed to add the following flags: -lm -lpthread -ldl

**Comment by PaulBatchelor** [comment]
Thanks for the catch. For whatever reason, my musl-based Alpine Linux system doesn't seem to need those. I've added them in dd45cc29a61b0cb51f2cc0653fe4a2941184852c
